<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $templates = [
            // ── Sayuran Daun (category_id = 1) ──
            [
                'category_id'        => 1,
                'name_id'            => 'Bayam',
                'scientific_name'    => 'Amaranthus cruentus',
                'family'             => 'Amaranthaceae',
                'germination_day'    => 3,
                'seedling_day'       => 10,
                'vegetative_day'     => 14,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 21,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => '4 L/m² per hari, 2x sehari (pagi & sore) saat kemarau',
                'sunlight'           => 'Full Sun',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Pakcoy',
                'scientific_name'    => 'Brassica rapa var. chinensis',
                'family'             => 'Brassicaceae',
                'germination_day'    => 3,
                'seedling_day'       => 14,
                'vegetative_day'     => 21,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 21,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => '2x sehari (pagi & sore) saat kemarau',
                'sunlight'           => 'Full Sun to Partial Shade',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Kangkung Darat',
                'scientific_name'    => 'Ipomoea aquatica',
                'family'             => 'Convolvulaceae',
                'germination_day'    => 3,
                'seedling_day'       => 7,
                'vegetative_day'     => 14,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 25,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 5.5,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 38.0,
                'water_requirement'  => '2x sehari (pagi & sore) saat kemarau',
                'sunlight'           => 'Full Sun',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Selada',
                'scientific_name'    => 'Lactuca sativa',
                'family'             => 'Asteraceae',
                'germination_day'    => 3,
                'seedling_day'       => 10,
                'vegetative_day'     => 21,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 55,
                'harvest_end_day'    => 65,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 5.0,
                'soil_ph_max'        => 6.5,
                'max_temperature'    => 30.0,
                'water_requirement'  => 'Rutin, jaga kelembapan tanah',
                'sunlight'           => 'Partial Shade',
                'recommended_months' => json_encode([4,5,6,7,8,9]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Seledri',
                'scientific_name'    => 'Apium graveolens',
                'family'             => 'Apiaceae',
                'germination_day'    => 7,
                'seedling_day'       => 14,
                'vegetative_day'     => 28,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 60,
                'harvest_end_day'    => 75,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 30.0,
                'water_requirement'  => 'Rutin, jaga kelembapan tanah',
                'sunlight'           => 'Partial Shade',
                'recommended_months' => json_encode([4,5,6,7,8,9]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            // ── Sayuran Buah (category_id = 2) ──
            [
                'category_id'        => 2,
                'name_id'            => 'Cabai Merah',
                'scientific_name'    => 'Capsicum annuum',
                'family'             => 'Solanaceae',
                'germination_day'    => 4,
                'seedling_day'       => 21,
                'vegetative_day'     => 28,
                'flowering_day'      => 45,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 75,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 5.5,
                'soil_ph_max'        => 6.8,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Harian saat persemaian, 150-250 ml/tanaman 2x sehari saat kering',
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['SOP Budidaya Cabai Merah (2014), Ditjen Hortikultura Kementan RI']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Cabai Rawit',
                'scientific_name'    => 'Capsicum frutescens',
                'family'             => 'Solanaceae',
                'germination_day'    => 5,
                'seedling_day'       => 30,
                'vegetative_day'     => 45,
                'flowering_day'      => 55,
                'fruiting_day'       => 65,
                'harvest_start_day'  => 75,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => '150-250 ml/tanaman 2x sehari saat kering',
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['SOP Budidaya Cabai Merah (2014), Ditjen Hortikultura Kementan RI']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Terung',
                'scientific_name'    => 'Solanum melongena',
                'family'             => 'Solanaceae',
                'germination_day'    => 3,
                'seedling_day'       => 25,
                'vegetative_day'     => 42,
                'flowering_day'      => 50,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 45,
                'harvest_end_day'    => 60,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Rutin, sesuai kebutuhan setelah transplantasi',
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['Teknik Sederhana Budidaya Terong (2021), Dinas Pertanian Kab. Demak']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Tomat',
                'scientific_name'    => 'Solanum lycopersicum',
                'family'             => 'Solanaceae',
                'germination_day'    => 4,
                'seedling_day'       => 21,
                'vegetative_day'     => 35,
                'flowering_day'      => 45,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 65,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 5.5,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Harian saat persemaian, sesuai kebutuhan setelah transplantasi',
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([4,5,6,7,8]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
        ];

        DB::table('plant_templates')->insert($templates);
    }
}
