<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $templates = [
            // ── Sayuran Daun (category_id = 1) ──
            [
                'category_id'        => 1,
                'name_id'            => 'Bayam',
                'scientific_name'    => 'Amaranthus cruentus',
                'family'             => 'Amaranthaceae',
                'germination_day'    => 3,
                'seedling_day'       => 10,
                'vegetative_day'     => 14,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 21,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2 hari sekali, jaga media lembap tidak tergenang',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2 hari sekali pada pagi hari. Pastikan tanah lembab namun tidak tergenang agar akar tidak busuk.',
                    'fertilizer'  => 'Pemupukan setiap 7 hari dengan pupuk organik cair atau NPK daun dosis rendah.',
                    'weeding'     => 'Penyiangan gulma dan penggemburan tanah setiap 10 hari.',
                    'pest_check'  => 'Inspeksi hama ulat grayak dan kutu daun setiap 7 hari.',
                ]),
                'sunlight'           => 'Sinar Matahari Penuh (6-8 jam)',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Pakcoy',
                'scientific_name'    => 'Brassica rapa var. chinensis',
                'family'             => 'Brassicaceae',
                'germination_day'    => 3,
                'seedling_day'       => 14,
                'vegetative_day'     => 21,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 21,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2 hari sekali saat tanah mulai kering',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2 hari sekali pada pagi hari. Hindari menyiram langsung ke tengah tajuk agar daun tidak busuk.',
                    'fertilizer'  => 'Pemupukan susulan setiap 7 hari dengan pupuk NPK terlarut.',
                    'pest_check'  => 'Inspeksi hama ulat daun dan kutu kebul setiap 7 hari.',
                    'weeding'     => 'Penyiangan gulma sekitar pangkal batang setiap 12 hari.',
                ]),
                'sunlight'           => 'Full Sun to Partial Shade',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Kangkung Darat',
                'scientific_name'    => 'Ipomoea aquatica',
                'family'             => 'Convolvulaceae',
                'germination_day'    => 3,
                'seedling_day'       => 7,
                'vegetative_day'     => 14,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 25,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 5.5,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 38.0,
                'water_requirement'  => 'Siram setiap 2 hari sekali, butuh kelembapan sedang hingga tinggi',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2 hari sekali pagi atau sore hari, jaga kelembaban tanah optimal.',
                    'fertilizer'  => 'Pemupukan setiap 7 hari setelah tanam dengan pupuk organik/NPK.',
                    'weeding'     => 'Penyiangan gulma liar setiap 10 hari.',
                ]),
                'sunlight'           => 'Full Sun',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Selada',
                'scientific_name'    => 'Lactuca sativa',
                'family'             => 'Asteraceae',
                'germination_day'    => 3,
                'seedling_day'       => 10,
                'vegetative_day'     => 21,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 55,
                'harvest_end_day'    => 65,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 5.0,
                'soil_ph_max'        => 6.5,
                'max_temperature'    => 30.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali secara merata',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali secara halus. Jangan biarkan tanah becek agar tidak busuk pangkal akar.',
                    'fertilizer'  => 'Pemupukan organik setiap 7 hari.',
                    'pest_check'  => 'Inspeksi siput dan kutu daun setiap 7 hari.',
                    'pruning'     => 'Pangkas daun tua di bagian bawah setiap 14 hari.',
                ]),
                'sunlight'           => 'Partial Shade',
                'recommended_months' => json_encode([4,5,6,7,8,9]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Seledri',
                'scientific_name'    => 'Apium graveolens',
                'family'             => 'Apiaceae',
                'germination_day'    => 7,
                'seedling_day'       => 14,
                'vegetative_day'     => 28,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 60,
                'harvest_end_day'    => 75,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 30.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali, jaga kelembapan tanah',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali secukupnya, pastikan drainase pot lancar.',
                    'fertilizer'  => 'Pemupukan NPK daun cair setiap 10 hari.',
                    'pruning'     => 'Pangkas tangkai daun tua terluar setiap 14 hari.',
                    'pest_check'  => 'Inspeksi bercak daun jamur septoria setiap 7 hari.',
                ]),
                'sunlight'           => 'Partial Shade',
                'recommended_months' => json_encode([4,5,6,7,8,9]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            // ── Sayuran Buah (category_id = 2) ──
            [
                'category_id'        => 2,
                'name_id'            => 'Cabai Merah',
                'scientific_name'    => 'Capsicum annuum',
                'family'             => 'Solanaceae',
                'germination_day'    => 4,
                'seedling_day'       => 21,
                'vegetative_day'     => 28,
                'flowering_day'      => 45,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 75,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 5.5,
                'soil_ph_max'        => 6.8,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali saat permukaan tanah kering',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali saat permukaan tanah mulai kering. Hindari genangan air berlebih.',
                    'fertilizer'  => 'Pemupukan setiap 7 hari (fase awal NPK daun, fase berbunga NPK buah/kalium tinggi).',
                    'pruning'     => 'Pangkas tunas air liar dan daun di bawah cabang utama (cabang Y) setiap 14 hari.',
                    'pest_check'  => 'Inspeksi kutu daun (thrips, kutu kebul) & tungau setiap 7 hari.',
                    'staking'     => 'Pasang ajir dan rapikan ikatan penyangga setiap 14 hari.',
                ]),
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['SOP Budidaya Cabai Merah (2014), Ditjen Hortikultura Kementan RI']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Cabai Rawit',
                'scientific_name'    => 'Capsicum frutescens',
                'family'             => 'Solanaceae',
                'germination_day'    => 5,
                'seedling_day'       => 30,
                'vegetative_day'     => 45,
                'flowering_day'      => 55,
                'fruiting_day'       => 65,
                'harvest_start_day'  => 75,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali saat media mulai kering',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali. Siram lebih jarang bila cuaca mendung atau lembab.',
                    'fertilizer'  => 'Pemupukan susulan setiap 7 hari dengan pupuk organik atau NPK.',
                    'pruning'     => 'Pangkas daun kering dan cabang tidak produktif setiap 14 hari.',
                    'pest_check'  => 'Inspeksi hama kutu daun dan keriting daun thrips setiap 7 hari.',
                    'staking'     => 'Pasang ajir bambu agar tanaman tidak roboh tertiup angin setiap 14 hari.',
                ]),
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['SOP Budidaya Cabai Merah (2014), Ditjen Hortikultura Kementan RI']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Terung',
                'scientific_name'    => 'Solanum melongena',
                'family'             => 'Solanaceae',
                'germination_day'    => 3,
                'seedling_day'       => 25,
                'vegetative_day'     => 42,
                'flowering_day'      => 50,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 45,
                'harvest_end_day'    => 60,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali secara mendalam',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali secara merata di area perakaran.',
                    'fertilizer'  => 'Pemupukan berkala setiap 7 hari untuk memacu pembungaan dan buah.',
                    'pruning'     => 'Pangkas daun kuning terbawah setiap 14 hari untuk mencegah jamur.',
                    'pest_check'  => 'Inspeksi hama kumbang daun dan ulat buah setiap 7 hari.',
                    'staking'     => 'Pasang ajir penyangga setiap 14 hari untuk menopang beban buah.',
                ]),
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['Teknik Sederhana Budidaya Terong (2021), Dinas Pertanian Kab. Demak']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Tomat',
                'scientific_name'    => 'Solanum lycopersicum',
                'family'             => 'Solanaceae',
                'germination_day'    => 4,
                'seedling_day'       => 21,
                'vegetative_day'     => 35,
                'flowering_day'      => 45,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 65,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 5.5,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali di bagian tanah (hindari daun basah)',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali langsung ke tanah. Jangan menyiram daun untuk menghindari hawar daun/jamur.',
                    'fertilizer'  => 'Pemupukan setiap 7 hari dengan pupuk kalium & kalsium saat berbuah.',
                    'pruning'     => 'Pangkas tunas air (suckers) di ketiak daun setiap 14 hari.',
                    'staking'     => 'Ikat batang pada ajir secara berkala setiap 14 hari.',
                    'pest_check'  => 'Inspeksi ulat buah dan lalat buah setiap 7 hari.',
                ]),
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([4,5,6,7,8]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
        ];

        DB::table('plant_templates')->insert($templates);
    }
}
