<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $templates = [
            // ── Sayuran Daun (category_id = 1) ──
            [
                'category_id'        => 1,
                'name_id'            => 'Bayam',
                'scientific_name'    => 'Amaranthus cruentus',
                'family'             => 'Amaranthaceae',
                'germination_day'    => 3,
                'seedling_day'       => 10,
                'vegetative_day'     => 14,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 21,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2 hari sekali, jaga media lembap tidak tergenang',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2 hari sekali pada pagi atau sore hari langsung ke tanah perakaran. Aturan Cuaca: Bila hari ini turun hujan lebat atau tanah masih basah, tunda siram; bila cuaca sangat terik kering, beri siraman lebih banyak.',
                    'fertilizer'  => 'Pemupukan susulan setiap 7 hari sekali dengan pupuk organik cair atau NPK daun dosis encer. Aturan Cuaca: Jangan memupuk cair saat hujan lebat agar pupuk tidak hanyut.',
                    'weeding'     => 'Pembersihan rumput liar (gulma) dan penggemburan tanah sekitar perakaran setiap 10 hari sekali.',
                    'pest_check'  => 'Pemeriksaan ulat grayak pemakan daun dan kutu daun setiap 7 hari sekali di bagian balik daun.',
                ]),
                'sunlight'           => 'Sinar Matahari Penuh (6-8 jam)',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Pakcoy',
                'scientific_name'    => 'Brassica rapa var. chinensis',
                'family'             => 'Brassicaceae',
                'germination_day'    => 3,
                'seedling_day'       => 14,
                'vegetative_day'     => 21,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 21,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2 hari sekali saat tanah mulai mengering',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2 hari sekali pada pagi hari di sekitar pangkal batang. Hindari menyiram langsung ke tengah tajuk daun agar tidak membusuk. Aturan Cuaca: Tunda siram bila hari hujan.',
                    'fertilizer'  => 'Pemupukan susulan setiap 7 hari sekali dengan pupuk NPK terlarut atau pupuk kompos organik cair.',
                    'pest_check'  => 'Pemeriksaan hama ulat daun dan kutu kebul putih setiap 7 hari sekali.',
                    'weeding'     => 'Pembersihan rumput liar di sekitar batang setiap 10 hari sekali.',
                ]),
                'sunlight'           => 'Full Sun to Partial Shade',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Kangkung Darat',
                'scientific_name'    => 'Ipomoea aquatica',
                'family'             => 'Convolvulaceae',
                'germination_day'    => 3,
                'seedling_day'       => 7,
                'vegetative_day'     => 14,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 25,
                'harvest_end_day'    => 30,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 5.5,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 38.0,
                'water_requirement'  => 'Siram setiap 2 hari sekali, butuh kelembapan sedang hingga tinggi',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2 hari sekali pagi atau sore hari untuk menjaga kelembapan tanah optimal. Aturan Cuaca: Tunda penyiraman jika hari hujan lebat.',
                    'fertilizer'  => 'Pemupukan susulan setiap 7 hari sekali setelah benih tumbuh dengan pupuk organik cair atau NPK daun encer.',
                    'weeding'     => 'Pembersihan rumput liar setiap 10 hari sekali agar kangkung tumbuh serempak dan lebat.',
                ]),
                'sunlight'           => 'Full Sun',
                'recommended_months' => json_encode([1,2,3,4,5,6,7,8,9,10,11,12]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Selada',
                'scientific_name'    => 'Lactuca sativa',
                'family'             => 'Asteraceae',
                'germination_day'    => 3,
                'seedling_day'       => 10,
                'vegetative_day'     => 21,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 45,
                'harvest_end_day'    => 60,
                'multiple_harvest'   => false,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 30.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali secara merata',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali dengan semprotan air halus. Jaga tanah tetap lembap sejuk, hindari genangan becek agar pangkal batang tidak busuk. Tunda bila hujan.',
                    'fertilizer'  => 'Pemupukan organik cair atau NPK daun dosis rendah setiap 7 hari sekali.',
                    'pest_check'  => 'Pemeriksaan siput, ulat tanah, dan kutu daun setiap 7 hari sekali.',
                    'pruning'     => 'Pangkas daun tua yang menguning atau menyentuh tanah setiap 14 hari sekali untuk mencegah busuk daun.',
                ]),
                'sunlight'           => 'Partial Shade',
                'recommended_months' => json_encode([4,5,6,7,8,9]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 1,
                'name_id'            => 'Seledri',
                'scientific_name'    => 'Apium graveolens',
                'family'             => 'Apiaceae',
                'germination_day'    => 7,
                'seedling_day'       => 14,
                'vegetative_day'     => 28,
                'flowering_day'      => null,
                'fruiting_day'       => null,
                'harvest_start_day'  => 60,
                'harvest_end_day'    => 75,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 30.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali, jaga kelembapan tanah',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali secukupnya. Pastikan tanah lembap dan saluran pembuangan air lancar agar akar tidak terendam busuk.',
                    'fertilizer'  => 'Pemupukan susulan NPK daun atau pupuk organik cair setiap 10 hari sekali di sekitar perakaran.',
                    'pruning'     => 'Pangkas tangkai daun tua di bagian terluar setiap 14 hari sekali untuk merangsang tunas baru di bagian tengah.',
                    'pest_check'  => 'Pemeriksaan bercak daun jamur septoria dan kutu daun setiap 7 hari sekali.',
                ]),
                'sunlight'           => 'Partial Shade',
                'recommended_months' => json_encode([4,5,6,7,8,9]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            // ── Sayuran Buah (category_id = 2) ──
            [
                'category_id'        => 2,
                'name_id'            => 'Cabai Merah',
                'scientific_name'    => 'Capsicum annuum',
                'family'             => 'Solanaceae',
                'germination_day'    => 4,
                'seedling_day'       => 21,
                'vegetative_day'     => 28,
                'flowering_day'      => 45,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 75,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali saat permukaan tanah kering',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali langsung ke tanah saat permukaan mulai kering. Aturan Cuaca: Tunda bila hari hujan lebat, tambah siraman saat musim kemarau terik.',
                    'fertilizer'  => 'Pemupukan setiap 7 hari sekali. Gunakan NPK daun saat masih kecil, lalu beralih ke pupuk tinggi Fosfor & Kalium saat mulai kuncup bunga. Tunda pemupukan cair bila hari hujan.',
                    'pruning'     => 'Pangkas tunas air liar di ketiak daun dan buang daun di bawah cabang Y pertama setiap 14 hari sekali agar tanaman fokus berbuah dan tidak lembap berjamur.',
                    'staking'     => 'Pasang tongkat ajir bambu dan ikat batang longgar setiap 14 hari sekali agar tanaman tidak tumbang atau patah saat berbuah lebat.',
                    'pest_check'  => 'Pemeriksaan kutu daun (thrips, kutu kebul, tungau) dan ulat buah setiap 7 hari sekali di balik helai daun.',
                ]),
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['SOP Budidaya Cabai Merah (2014), Ditjen Hortikultura Kementan RI']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Cabai Rawit',
                'scientific_name'    => 'Capsicum frutescens',
                'family'             => 'Solanaceae',
                'germination_day'    => 5,
                'seedling_day'       => 30,
                'vegetative_day'     => 45,
                'flowering_day'      => 55,
                'fruiting_day'       => 65,
                'harvest_start_day'  => 75,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali saat media mulai kering',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali langsung ke pangkal tanah. Kurangi penyiraman saat cuaca mendung atau sering hujan untuk mencegah kerontokan bunga dan busuk akar.',
                    'fertilizer'  => 'Pemupukan susulan setiap 7 hari sekali dengan pupuk kandang matang atau pupuk NPK terlarut secara bergantian.',
                    'pruning'     => 'Pangkas ranting kering, daun tua menguning, dan tunas liar setiap 14 hari sekali agar sirkulasi udara optimal.',
                    'staking'     => 'Pasang tiang ajir dan rapikan ikatan penyangga setiap 14 hari sekali agar tanaman kokoh dan tegak.',
                    'pest_check'  => 'Pemeriksaan keriting daun thrips, kutu putih, dan lalat buah setiap 7 hari sekali.',
                ]),
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['SOP Budidaya Cabai Merah (2014), Ditjen Hortikultura Kementan RI']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Terung',
                'scientific_name'    => 'Solanum melongena',
                'family'             => 'Solanaceae',
                'germination_day'    => 3,
                'seedling_day'       => 25,
                'vegetative_day'     => 42,
                'flowering_day'      => 50,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 50,
                'harvest_end_day'    => 65,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali secara mendalam',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali secara merata di area perakaran tanah. Aturan Cuaca: Tunda penyiraman bila hari turun hujan lebat.',
                    'fertilizer'  => 'Pemupukan berkala setiap 7 hari sekali dengan pupuk NPK seimbang untuk memacu pertumbuhan cabang dan pembesaran buah terung.',
                    'pruning'     => 'Pangkas daun-daun tua terbawah yang menyentuh tanah setiap 14 hari sekali untuk mencegah penularan penyakit jamur dari tanah.',
                    'staking'     => 'Pasang tongkat ajir kokoh setiap 14 hari sekali untuk menopang cabang terung yang sarat buah agar tidak patah.',
                    'pest_check'  => 'Pemeriksaan hama kutu daun, kumbang perusak daun, dan ulat penggerek buah setiap 7 hari sekali.',
                ]),
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([3,4,5,9,10,11]),
                'source_refs'        => json_encode(['Teknik Sederhana Budidaya Terong (2021), Dinas Pertanian Kab. Demak']),
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'category_id'        => 2,
                'name_id'            => 'Tomat',
                'scientific_name'    => 'Solanum lycopersicum',
                'family'             => 'Solanaceae',
                'germination_day'    => 4,
                'seedling_day'       => 21,
                'vegetative_day'     => 35,
                'flowering_day'      => 45,
                'fruiting_day'       => 55,
                'harvest_start_day'  => 65,
                'harvest_end_day'    => 80,
                'multiple_harvest'   => true,
                'soil_ph_min'        => 6.0,
                'soil_ph_max'        => 7.0,
                'max_temperature'    => 35.0,
                'water_requirement'  => 'Siram setiap 2-3 hari sekali di bagian tanah (hindari daun basah)',
                'care_rules'         => json_encode([
                    'watering'    => 'Siram setiap 2-3 hari sekali langsung ke permukaan tanah (jangan menyiram daunnya untuk mencegah jamur hawar daun busuk). Tunda jika hari hujan.',
                    'fertilizer'  => 'Pemupukan setiap 7 hari sekali dengan pupuk tinggi Kalium dan Kalsium untuk mencegah pantat buah busuk (blossom end rot) dan buah pecah.',
                    'pruning'     => 'Pangkas tunas air liar (anak daun di ketiak batang) secara teratur setiap 14 hari sekali agar buah berukuran besar dan manis.',
                    'staking'     => 'Pasang ajir bambu dan ikat batang tomat perlahan setiap 14 hari sekali mengikuti pertumbuhan tingginya.',
                    'pest_check'  => 'Pemeriksaan ulat pemakan buah dan lalat buah setiap 7 hari sekali.',
                ]),
                'sunlight'           => 'High/Full',
                'recommended_months' => json_encode([4,5,6,7,8]),
                'source_refs'        => json_encode(['Petunjuk Teknis Budidaya Tanaman Sayuran (2014), BALITSA']),
                'created_at' => $now, 'updated_at' => $now,
            ],
        ];

        foreach ($templates as $template) {
            DB::table('plant_templates')->updateOrInsert(
                ['name_id' => $template['name_id']],
                $template
            );
        }
    }
}
